backend:
  name: git-gateway
  branch: exercise-7-deploy

media_folder: static/images
public_folder: /images

collections:
  - name: product
    label: "Products"
    folder: products
    create: true
    slug: "{{slug}}"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: "name", label: "Name", widget: string }
      - { name: "body", label: "Body", widget: markdown}
      - { label: "Gender", name: "gender", widget: "select", options: ["M", "W"] }
      - {
        label: Product Variants,
        name: variants,
        widget: list,
        fields: [{ label: Photo, name: image, widget: image }, { label: Price, name: price, widget: number, valueType: "float" }, { label: Stock, name: qty, widget: number, valueType: "int" }, { label: "Sizes", name: "size", widget: "select", options: ["S", "M", "L"] }],
      }
